// <auto-generated />
// Generated from WebUi/bridge-contract.json by Tools/Generate-BridgeContract.ps1.
using System.Collections.Generic;

namespace OpenClawDebugger;

internal static class BridgeContractGenerated
{
    public const int ProtocolVersion = 2;
    public static readonly IReadOnlyDictionary<string, BridgeCommandDefinition> Commands =
        new Dictionary<string, BridgeCommandDefinition>(StringComparer.Ordinal)
        {
            ["initialize"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "local",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["saveSettings"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "settings",
                TimeoutMs = 30000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["host"] = "string",
                    ["username"] = "string",
                    ["port"] = "integer",
                    ["workspacePath"] = "string",
                    ["stickersPath"] = "string",
                    ["backupRetentionCount"] = "integer",
                }
            },
            ["setTheme"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "settings",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["theme"] = "string",
                }
            },
            ["connect"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "connection",
                TimeoutMs = 600000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["disconnect"] = new BridgeCommandDefinition
            {
                Mode = "control",
                Domain = "connection",
                TimeoutMs = 30000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["readMemory"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "read",
                TimeoutMs = 180000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["path"] = "string",
                }
            },
            ["saveMemory"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "edit",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["path"] = "string",
                    ["expectedSha256"] = "string",
                    ["text"] = "string",
                }
            },
            ["getModels"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "model",
                TimeoutMs = 180000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["testModelLatency"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "model",
                TimeoutMs = 1800000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["models"] = "array",
                }
            },
            ["setModelOrder"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "model",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["primary"] = "string",
                    ["fallbacks"] = "array",
                }
            },
            ["addModel"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "model",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["modelRef"] = "string",
                    ["alias"] = "string",
                    ["displayName"] = "string",
                    ["baseUrl"] = "string",
                    ["apiKey"] = "string",
                }
            },
            ["readSticker"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "read",
                TimeoutMs = 180000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["path"] = "string",
                }
            },
            ["readStickerThumbnail"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "thumbnail",
                TimeoutMs = 180000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["path"] = "string",
                }
            },
            ["previewStickerRows"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "edit",
                TimeoutMs = 30000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["rows"] = "array",
                }
            },
            ["saveStickerRows"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "edit",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["rows"] = "array",
                }
            },
            ["saveStickerRaw"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "edit",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["catalog"] = "string",
                    ["manifest"] = "string",
                }
            },
            ["beginStickerUpload"] = new BridgeCommandDefinition
            {
                Mode = "uploadStart",
                Domain = "edit",
                TimeoutMs = 30000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["fileName"] = "string",
                    ["size"] = "integer",
                }
            },
            ["appendStickerUpload"] = new BridgeCommandDefinition
            {
                Mode = "uploadChunk",
                Domain = "upload",
                TimeoutMs = 60000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["uploadId"] = "string",
                    ["offset"] = "integer",
                    ["contentBase64"] = "string",
                    ["sha256"] = "string",
                }
            },
            ["commitStickerUpload"] = new BridgeCommandDefinition
            {
                Mode = "uploadFinalize",
                Domain = "edit",
                TimeoutMs = 1800000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["uploadId"] = "string",
                }
            },
            ["cancelStickerUpload"] = new BridgeCommandDefinition
            {
                Mode = "uploadCancel",
                Domain = "control",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["uploadId"] = "string",
                }
            },
            ["renameSticker"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "edit",
                TimeoutMs = 300000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["oldFileName"] = "string",
                    ["newFileName"] = "string",
                }
            },
            ["backup"] = new BridgeCommandDefinition
            {
                Mode = "remote",
                Domain = "backup",
                TimeoutMs = 7200000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["toggleBackupPause"] = new BridgeCommandDefinition
            {
                Mode = "control",
                Domain = "control",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["cancelBackup"] = new BridgeCommandDefinition
            {
                Mode = "control",
                Domain = "control",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["openPrivateFolder"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "local",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["openBackupFolder"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "local",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["exportLogs"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "local",
                TimeoutMs = 60000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["draftState"] = new BridgeCommandDefinition
            {
                Mode = "local",
                Domain = "local",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["dirty"] = "boolean",
                }
            },
            ["close"] = new BridgeCommandDefinition
            {
                Mode = "control",
                Domain = "control",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                }
            },
            ["cancelOperation"] = new BridgeCommandDefinition
            {
                Mode = "control",
                Domain = "control",
                TimeoutMs = 15000,
                Payload = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["operationId"] = "string",
                }
            },
        };
}
