param(
    [string]$InputPath = (Join-Path $PSScriptRoot '..\WebUi\bridge-contract.json'),
    [string]$CSharpPath = (Join-Path $PSScriptRoot '..\BridgeContractGenerated.cs'),
    [string]$JavaScriptPath = (Join-Path $PSScriptRoot '..\WebUi\bridge-contract.generated.js')
)

$ErrorActionPreference = 'Stop'

function ConvertTo-CSharpString([AllowNull()][string]$Value) {
    if ($null -eq $Value) { return 'null' }
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$contract = Get-Content -LiteralPath $InputPath -Raw | ConvertFrom-Json
if ($null -eq $contract.protocolVersion -or $null -eq $contract.commands) {
    throw '桥接协议必须包含 protocolVersion 和 commands。'
}

$lines = [System.Collections.Generic.List[string]]::new()
[void]$lines.Add('// <auto-generated />')
[void]$lines.Add('// Generated from WebUi/bridge-contract.json by Tools/Generate-BridgeContract.ps1.')
[void]$lines.Add('using System.Collections.Generic;')
[void]$lines.Add('')
[void]$lines.Add('namespace OpenClawDebugger;')
[void]$lines.Add('')
[void]$lines.Add('internal static class BridgeContractGenerated')
[void]$lines.Add('{')
[void]$lines.Add("    public const int ProtocolVersion = $([int]$contract.protocolVersion);")
[void]$lines.Add('    public static readonly IReadOnlyDictionary<string, BridgeCommandDefinition> Commands =')
[void]$lines.Add('        new Dictionary<string, BridgeCommandDefinition>(StringComparer.Ordinal)')
[void]$lines.Add('        {')

foreach ($property in $contract.commands.psobject.Properties) {
    $name = ConvertTo-CSharpString $property.Name
    $definition = $property.Value
    $mode = ConvertTo-CSharpString ([string]$definition.mode)
    $domain = if ($null -eq $definition.domain) { 'null' } else { ConvertTo-CSharpString ([string]$definition.domain) }
    $timeout = [int]$definition.timeoutMs
    [void]$lines.Add("            [$name] = new BridgeCommandDefinition")
    [void]$lines.Add('            {')
    [void]$lines.Add("                Mode = $mode,")
    [void]$lines.Add("                Domain = $domain,")
    [void]$lines.Add("                TimeoutMs = $timeout,")
    [void]$lines.Add('                Payload = new Dictionary<string, string>(StringComparer.Ordinal)')
    [void]$lines.Add('                {')
    if ($null -ne $definition.payload) {
        foreach ($payload in $definition.payload.psobject.Properties) {
            [void]$lines.Add("                    [$(ConvertTo-CSharpString $payload.Name)] = $(ConvertTo-CSharpString ([string]$payload.Value)),")
        }
    }
    [void]$lines.Add('                }')
    [void]$lines.Add('            },')
}

[void]$lines.Add('        };')
[void]$lines.Add('}')

$csharpDirectory = Split-Path -Parent $CSharpPath
New-Item -ItemType Directory -Force -Path $csharpDirectory | Out-Null
[System.IO.File]::WriteAllLines([System.IO.Path]::GetFullPath($CSharpPath), $lines, [System.Text.UTF8Encoding]::new($false))

$json = $contract | ConvertTo-Json -Depth 30
$javascript = @"
// <auto-generated />
// Generated from bridge-contract.json by Tools/Generate-BridgeContract.ps1.
(function () {
  'use strict';
  window.OpenClawBridgeContract = Object.freeze($json);
})();
"@
$javascriptDirectory = Split-Path -Parent $JavaScriptPath
New-Item -ItemType Directory -Force -Path $javascriptDirectory | Out-Null
[System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($JavaScriptPath), $javascript, [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $CSharpPath and $JavaScriptPath"
